paymentflowrules :
  DOTP : 
    - key: txn_s2s_flow
      operator: EQ
      value: "02"
    - key : temp
      operator: EQ
      value : "alias"
  TPV : 
    - key : bankDetails
      operator: MAP
      value : "beneficiarydetail"
