paymentflowrules :
  TPV : 
    - key: txn_s2s_flow
      operator: EQ
      value: "02"
    - key : temp
      operator: EQ
      value : "23"
  MANDATE : 
    - key : "frequency"
      operator: MAP
      value : "frequency"
